version: '3'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ai-chatbot-frontend:latest
    container_name: AI-chatbot-frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
